# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "functions-js"
client_id = "ee521f0989d0a98155d243e87525b9d9"
application_url = "https://plumbing-cosmetic-coast-slope.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://plumbing-cosmetic-coast-slope.trycloudflare.com/auth/callback",
  "https://plumbing-cosmetic-coast-slope.trycloudflare.com/auth/shopify/callback",
  "https://plumbing-cosmetic-coast-slope.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "inmers.myshopify.com"
