name = "test-extension"
type = "product_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/app/test-extension/:functionId/new"
details = "/app/test-extension/:functionId/:id"
